
export const ADDRESS = {
  FETCHED: 'ADDRESS_FETCHED',
  UNFETCHED: 'ADDRESS_UNFETCHED',
  FETCHING: 'ADDRESS_FETCHING',
  ERROR_CHANGED: 'ADDRESS_ERROR_CHANGED',
  
  LIST_FETCHED: 'ADDRESSES_LIST_FETCHED',
  LIST_UNFETCHED: 'ADDRESSES_LIST_UNFETCHED',
  LIST_FETCHING: 'ADDRESSES_FETCHING',
  LIST_ERROR_CHANGED: 'ADDRESSES_ERROR_CHANGED',

  LOCATIONS_LIST_FETCHED: 'LOCATIONS_LIST_FETCHED',
  LOCATIONS_LIST_FETCHING: 'LOCATIONS_LIST_FETCHING',
  LOCATIONS_LIST_ERROR_CHANGED: 'LOCATIONS_LIST_ERROR_CHANGED'
};
