
export const ADMIN = {
  AUTHED: 'AUTHED',
  UNAUTHED: 'UNAUTHED',
  AUTH_FAILED: 'AUTH_FAILED',
  UPDATED: 'UPDATED',
  UPDATE_FAILED: 'UPDATE_FAILED',
  RESET_PASSWORD: 'RESET_PASSWORD',
  RESET_PASSWORD_FAILED: 'RESET_PASSWORD_FAILED',

  FETCHED: 'USER_FETCHED',
  FETCH_STATUS_CHANGED: 'USER_FETCH_STATUS_CHANGED',
};

