
export const CART = {
  ITEM_ADDED: 'CART_ITEM_ADDED',
  ITEM_REMOVED: 'CART_ITEM_REMOVED',
  ITEMS_REPLACED: 'CART_ITEMS_REPLACED',
  ITEM_QUANTITY_CHANGED: 'CART_ITEM_QUANTITY_CHANGED',

  DELIVERY_METHOD_CHOOSEN: 'DELIVERY_METHOD_CHOOSEN',
  DELIVERY_ROUTE_CHOOSEN: 'DELIVERY_ROUTE_CHOOSEN',
  DELIVERY_ADDRESS_CHOOSEN: 'DELIVERY_ADDRESS_CHOOSEN',
  DISCOUNT_CHOOSEN: 'DISCOUNT_CHOOSEN',
  PAYMENT_METHOD_CHOOSEN: 'PAYMENT_METHOD_CHOOSEN',

};
