
export const CATEGORY = {
  UNFETCHED: 'CATEGORY_UNFETCHED',
  FETCHED: 'CATEGORY_FETCHED',
  FETCHING: 'CATEGORY_FETCHING',
  ERROR_CHANGED: 'CATEGORY_ERROR_CHANGED',

  LIST_FETCHED: 'CATEGORIES_FETCHED',
  LIST_FETCHING: 'CATEGORIES_FETCHING',
  LIST_ERROR_CHANGED: 'CATEGORIES_ERROR_CHANGED',

  STORES_LIST_FETCHED: 'STORE_CATEGORIES_FETCHED',
  STORES_LIST_FETCHING: 'STORES_CATEGORIES_FETCHING',
  STORES_LIST_ERROR_CHANGED: 'STORES_CATEGORIES_ERROR_CHANGED',

  PRODUCTS_LIST_FETCHED: 'PRODUCT_CATEGORIES_FETCHED',
  PRODUCTS_LIST_FETCHING: 'PRODUCT_CATEGORIES_FETCHING',
  PRODUCTS_LIST_ERROR_CHANGED: 'PRODUCT_CATEGORIES_FETCH_FAILED',

  SUB_UNFETCHED: 'SUB_CATEGORY_UNFETCHED',
  SUB_FETCHED: 'SUB_CATEGORY_FETCHED',
  SUB_FETCHING: 'SUB_CATEGORY_FETCHING',
  SUB_ERROR_CHANGED: 'SUB_CATEGORY_ERROR_CHANGED',
};
