
export const CUSTOMER = {
  AUTHED: 'CUSTOMER_AUTHED',
  UNAUTHED: 'CUSTOMER_UNAUTHED',

  FETCHED: 'CUSTOMER_FETCHED',
  UNFETCHED: 'CUSTOMER_UNFETCHED',
  FETCHING: 'CUSTOMER_FETCHING',
  ERROR_CHANGED: 'CUSTOMER_ERROR_CHANGED',

  LIST_FETCHED: 'CUSTOMERS_FETCHED',
  LIST_UNFETCHED: 'CUSTOMERS_UNFETCHED',
  LIST_FETCHING: 'CUSTOMERS_FETCHING',
  LIST_ERROR_CHANGED: 'CUSTOMERS_ERROR_CHANGED',
};
