
export const DELIVERY_ROUTE = {
  FETCHED: 'DELIVERY_ROUTE_FETCHED',
  UNFETCHED: 'DELIVERY_ROUTE_UNFETCHED',
  FETCHING: 'DELIVERY_ROUTE_FETCHING',
  ERROR_CHANGED: 'DELIVERY_ROUTE_ERROR_CHANGED',

  LIST_FETCHED: 'DELIVERY_ROUTES_FETCHED',
  LIST_UNFETCHED: 'DELIVERY_ROUTES_UNFETCHED',
  LIST_FETCHING: 'DELIVERY_ROUTES_FETCHING',
  LIST_ERROR_CHANGED: 'DELIVERY_ROUTES_ERROR_CHANGED',

  LOCATION_CREATED: 'DELIVERY_ROUTE_LOCATION_CREATED',
  LOCATION_UPDATED: 'DELIVERY_ROUTE_LOCATION_UPDATED',
  LOCATION_DELETED: 'DELIVERY_ROUTE_LOCATION_DELETED',
  LOCATION_FETCHED: 'DELIVERY_ROUTE_LOCATION_FETCHED',
  LOCATION_UNFETCHED: 'DELIVERY_ROUTE_LOCATION_UNFETCHED',
  LOCATION_FETCHING: 'DELIVERY_ROUTE_LOCATION_FETCHING',
  LOCATION_ERROR_CHANGED: 'DELIVERY_ROUTE_LOCATION_ERROR_CHANGED',

  WEIGHT_CREATED: 'DELIVERY_ROUTE_WEIGHT_CREATED',
  WEIGHT_UPDATED: 'DELIVERY_ROUTE_WEIGHT_UPDATED',
  WEIGHT_DELETED: 'DELIVERY_ROUTE_WEIGHT_DELETED',
  WEIGHT_FETCHED: 'DELIVERY_ROUTE_WEIGHT_FETCHED',
  WEIGHT_UNFETCHED: 'DELIVERY_ROUTE_WEIGHT_UNFETCHED',
  WEIGHT_FETCHING: 'DELIVERY_ROUTE_WEIGHT_FETCHING',
  WEIGHT_ERROR_CHANGED: 'DELIVERY_ROUTE_WEIGHT_ERROR_CHANGED',
};
