
export const DISCOUNT = {
  FETCHED: 'DISCOUNT_FETCHED',
  UNFETCHED: 'DISCOUNT_UNFETCHED',
  FETCHING: 'DISCOUNT_FETCHING',
  ERROR_CHANGED: 'DISCOUNT_ERROR_CHANGED',

  LIST_FETCHED: 'DISCOUNTS_FETCHED',
  LIST_UNFETCHED: 'DISCOUNTS_UNFETCHED',
  LIST_FETCHING: 'DISCOUNTS_FETCHING',
  LIST_ERROR_CHANGED: 'DISCOUNTS_ERROR_CHANGED',

  PRODUCT_CREATED: 'DISCOUNT_PRODUCT_CREATED',
  PRODUCT_DELETED: 'DISCOUNT_PRODUCT_DELETED',
  
  PRODUCT_LIST_FETCHED: 'DISCOUNT_PRODUCTS_FETCHED',
  PRODUCT_LIST_UNFETCHED: 'DISCOUNT_PRODUCTS_UNFETCHED',
  PRODUCT_LIST_FETCHING: 'DISCOUNT_ PRODUCTS_FETCHING',
  PRODUCT_LIST_ERROR_CHANGED: 'DISCOUNT_PRODUCTS_ERROR_CHANGED',
};
