
export const MESSAGE = {

  FETCHED: 'MESSAGE_FETCHED',
  UNFETCHED: 'MESSAGE_UNFETCHED',
  FETCHING: 'MESSAGE_FETCHING',
  ERROR_CHANGED: 'MESSAGE_ERROR_CHANGED',

  LIST_FETCHED: 'MESSAGES_FETCHED',
  LIST_UNFETCHED: 'MESSAGES_UNFETCHED',
  LIST_FETCHING: 'MESSAGES_FETCHING',
  LIST_ERROR_CHANGED: 'MESSAGES_ERROR_CHANGED',
  
  UNRECEIVED_COUNT_FETCHED: 'UNRECEIVED_COUNT_FETCHED',

  CHAT_LIST_FETCHED: 'CHATS_FETCHED',
  CHAT_LIST_UNFETCHED: 'CHATS_UNFETCHED',
  CHAT_LIST_FETCHING: 'CHATS_FETCHING',
  CHAT_LIST_ERROR_CHANGED: 'CHATS_ERROR_CHANGED',

  SENT: 'MESSAGE_SENT',
  RECEIVED: 'MESSAGE_RECEIVED',
};
