
export const PRODUCT = {
  FETCHED: 'PRODUCT_FETCHED',
  UNFETCHED: 'PRODUCT_UNFETCHED',
  FETCHING: 'PRODUCT_FETCHING',
  ERROR_CHANGED: 'PRODUCT_ERROR_CHANGED',
  
  LIST_FETCHED: 'PRODUCTS_FETCHED',
  LIST_UNFETCHED: 'PRODUCTS_UNFETCHED',
  LIST_FETCHING: 'PRODUCTS_FETCHING',
  LIST_ERROR_CHANGED: 'PRODUCTS_ERROR_CHANGED',

  RELATED_LIST_FETCHED: 'RELATED_PRODUCTS_FETCHED',
  RELATED_LIST_ERROR_CHANGED: 'RELATED_PRODUCTS_ERROR_CHANGED',
  RELATED_LIST_FETCHING: 'RELATED_PRODUCTS_FETCHING',

  FAVORITED: 'PRODUCT_FAVORITED',
  UNFAVORITED: 'PRODUCT_UNFAVORITED',

  VARIANT_CREATED: 'PRODUCT_VARIANT_CREATED',
  VARIANT_UPDATED: 'PRODUCT_VARIANT_UPDATED',
  VARIANT_DELETED: 'PRODUCT_VARIANT_DELETED',
  VARIANT_FETCHED: 'PRODUCT_VARIANT_FETCHED',
  VARIANT_UNFETCHED: 'PRODUCT_VARIANT_UNFETCHED',
  VARIANT_FETCHING: 'PRODUCT_VARIANT_FETCHING',
  VARIANT_ERROR_CHANGED: 'PRODUCT_VARIANT_ERROR_CHANGED',
};

export const getProductVariantFetchStatusAction = (fetchStatus, id, loading) => ({
  type: PRODUCT.VARIANT_FETCH_STATUS_CHANGED,
  payload: {
    fetchStatus, id, loading
  }
});

export const getProductsListFetchStatusAction = (fetchStatus, loading) => ({
  type: PRODUCT.LIST_FETCH_STATUS_CHANGED,
  payload: {
    fetchStatus, loading
  }
});

export const getRelatedProductsListFetchStatusAction = (fetchStatus, loading) => ({
  type: PRODUCT.RELATED_LIST_FETCH_STATUS_CHANGED,
  payload: {
    fetchStatus, loading
  }
});

