
export const PROMOTION = {

  FETCHED: 'PROMOTION_FETCHED',
  UNFETCHED: 'PROMOTION_UNFETCHED',

  LIST_FETCHED: 'PROMOTIONS_FETCHED',
  LIST_UNFETCHED: 'PROMOTIONS_UNFETCHED',
  LIST_FETCHING: 'PROMOTIONS_FETCHING',
  LIST_ERROR_CHANGED: 'PROMOTIONS_FETCH_FAILED',
};
