
export const REVIEW = {
  UNFETCH: 'REVIEW_UNFETCH',
  FETCHED: 'REVIEW_FETCHED',
  FETCH_STATUS_CHANGED: 'REVIEW_FETCH_STATUS_CHANGED',
  
  LIST_UNFETCHED: 'REVIEWS_UNFETCHED',
  LIST_FETCHING: 'REVIEWS_FETCHING',
  LIST_ERROR_CHANGED: 'REVIEWS_ERROR_CHANGED',
  LIST_FETCHED: 'REVIEWS_FETCHED',

  CREATED: 'REVIEW_CREATED',
  UPDATED: 'REVIEW_UPDATED',
  DELETED: 'REVIEW_DELETED'
};

export const getReviewsListFetchStatusAction = (fetchStatus, loading) => ({
  type: REVIEW.LIST_FETCH_STATUS_CHANGED,
  payload: {
    fetchStatus, loading
  }
});
