
export const REVIEW = {
  UNFETCH: 'REVIEW_UNFETCH',
  FETCHED: 'REVIEW_FETCHED',
  FETCH_STATUS_CHANGED: 'REVIEW_FETCH_STATUS_CHANGED',
  LIST_FETCHED: 'REVIEWS_FETCHED',
  LIST_FETCH_STATUS_CHANGED: 'REVIEWS_FETCH_STATUS_CHANGED',
};

export const getReviewsListFetchStatusAction = (payload) => ({
  type: REVIEW.LIST_FETCH_STATUS_CHANGED,
  payload
});
