
export const STORE = {
  AUTHED: 'STORE_AUTHED',
  UNAUTHED: 'STORE_UNAUTHED',

  FETCHED: 'STORE_FETCHED',
  UNFETCHED: 'STORE_UNFETCHED',
  FETCHING: 'STORE_FETCHING',
  ERROR_CHANGED: 'STORE_ERROR_CHANGED',

  LIST_FETCHED: 'STORES_FETCHED',
  LIST_UNFETCHED: 'STORES_UNFETCHED',
  LIST_FETCHING: 'STORES_FETCHING',
  LIST_ERROR_CHANGED: 'STORES_ERROR_CHANGED',
};
