
export const TRANSACTION = {
  UNFETCHED: 'TRANSACTION_UNFETCHED',
  FETCHED: 'TRANSACTION_FETCHED',
  FETCH_STATUS_CHANGED: 'TRANSACTION_FETCH_STATUS_CHANGED',
  LIST_UNFETCHED: 'TRANSACTIONS_UNFETCHED',
  LIST_FETCHED: 'TRANSACTIONS_FETCHED',
  LIST_FETCH_STATUS_CHANGED: 'TRANSACTIONS_FETCH_STATUS_CHANGED',
};

export const getTransactionFetchStatusAction = (payload) => ({
  type: TRANSACTION.FETCH_STATUS_CHANGED,
  payload
});

export const getTransactionsListFetchStatusAction = (payload) => ({
  type: TRANSACTION.LIST_FETCH_STATUS_CHANGED,
  payload
});


