
export const TRANSACTION = {
  FETCHED: 'TRANSACTION_FETCHED',
  UNFETCHED: 'TRANSACTION_UNFETCHED',
  FETCHING: 'TRANSACTION_FETCHING',
  ERROR_CHANGED: 'TRANSACTION_ERROR_CHANGED',

  BALANCE_WITHDRAWN: 'TRANSACTION_BALANCE_WITHDRAWN',
  BALANCE_FETCHED: 'TRANSACTION_BALANCE_FETCHED',
  BALANCE_UNFETCHED: 'TRANSACTION_BALANCE_UNFETCHED',
  BALANCE_FETCHING: 'TRANSACTION_BALANCE_FETCHING',
  BALANCE_ERROR_CHANGED: 'TRANSACTION_BALANCE_ERROR_CHANGED',
  
  LIST_FETCHED: 'TRANSACTIONS_FETCHED',
  LIST_FETCHING: 'TRANSACTIONS_FETCHING',
  LIST_ERROR_CHANGED: 'TRANSACTIONS_ERROR_CHANGED',
  LIST_UNFETCHED: 'TRANSACTIONS_UNFETCHED',
};
