
const NetworkErrorCodes = {
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  UNAUTHORIZED: 'UNAUTHORIZED',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  NO_NETWORK_CONNECTION: 'NO_NETWORK_CONNECTION'
};

export default NetworkErrorCodes;
