
export const FETCH_STATUSES = {
  LOADING: 'LOADING',
  ERROR: 'ERROR',
  EMPTY: 'EMPTY',
  MORE: 'MORE',
  DONE: 'DONE',
};

export const HOME = {
  CATEGORIES_FETCHED: 'CATEGORIES_FETCHED',
  CATEGORIES_FETCH_STATUS_CHANGED: 'CATEGORIES_FETCH_STATUS_CHANGED',
  STORES_FETCHED: 'STORES_FETCHED',
  STORES_FETCH_STATUS_CHANGED: 'STORES_FETCH_STATUS_CHANGED'
};

export const CATEGORIES = {
  STORES_FETCHED: 'STORES_FETCHED',
  STORES_FETCH_STATUS_CHANGED: 'STORES_FETCH_STATUS_CHANGED',
  PRODUCTS_FETCHED: 'PRODUCTS_FETCHED',
  PRODUCTS_FETCH_STATUS_CHANGED: 'PRODUCTS_FETCH_STATUS_CHANGED'
};

export const STORE = {
  UNFETCH: 'STORE_UNFETCH',
  FETCHED: 'STORE_FETCHED',
  FETCH_STATUS_CHANGED: 'STORE_FETCH_STATUS_CHANGED',
  PRODUCTS_FETCHED: 'PRODUCTS_FETCHED',
  PRODUCTS_FETCH_STATUS_CHANGED: 'PRODUCTS_FETCH_STATUS_CHANGED'
};

export const PRODUCT = {
  UNFETCH: 'PRODUCT_UNFETCH',
  FETCHED: 'PRODUCT_FETCHED',
  FETCH_STATUS_CHANGED: 'PRODUCT_FETCH_STATUS_CHANGED',
  FILTER_CHANGED: 'PRODUCT_FILTER_CHANGED'
};

export const SEARCH = {
  QUERY_CHANGED: 'QUERY_CHANGED',
};

export const CART = {
  ITEM_ADDED: 'CART_ITEM_ADDED',
  ITEM_REMOVED: 'CART_ITEM_REMOVED',
  ITEM_QUANTITY_CHANGED: 'CART_ITEM_QUANTITY_CHANGED'
}

