
export const FETCH_STATUSES = {
  PENDING: 'PENDING',
  LOADING: 'LOADING',
  ERROR: 'ERROR',
  EMPTY: 'EMPTY',
  MORE: 'MORE',
  DONE: 'DONE',
};

export const getFormRequestFailedAction = (type) => ({
  type,
  payload: { form: '_errors.Something_went_wrong' }
});

export const USER = {
  AUTHED: 'AUTHED',
  AUTH_FAILED: 'AUTH_FAILED',
  UPDATED: 'UPDATED',
  UPDATE_FAILED: 'UPDATE_FAILED',
  RESET_PASSWORD: 'RESET_PASSWORD',
  RESET_PASSWORD_FAILED: 'RESET_PASSWORD_FAILED',

  FETCHED: 'USER_FETCHED',
  FETCH_STATUS_CHANGED: 'USER_FETCH_STATUS_CHANGED',
};

export const USER_ADDRESS = {
  FETCHED: 'USER_ADDRESS_FETCHED',
  UNFETCHED: 'USER_ADDRESS_UNFETCHED',
  FETCH_STATUS_CHANGED: 'USER_ADDRESS_FETCH_STATUS_CHANGED',
  LIST_FETCHED: 'USER_ADDRESS_LIST_FETCHED',
  LIST_FETCH_STATUS_CHANGED: 'USER_ADDRESS_LIST_FETCH_STATUS_CHANGED',
};

export const getUserAddressListFetchStatusAction = (payload) => ({
  type: USER_ADDRESS.LIST_FETCH_STATUS_CHANGED,
  payload
});

export const getUserAddressFetchStatusAction = (payload) => ({
  type: USER_ADDRESS.FETCH_STATUS_CHANGED,
  payload
});

export const CATEGORIES = {
  UNFETCH: 'CATEGORIES_UNFETCH',
  FETCHED: 'CATEGORIES_FETCHED',
  FETCH_STATUS_CHANGED: 'CATEGORIES_FETCH_STATUS_CHANGED', 
  LIST_FETCHED: 'CATEGORIES_FETCHED',
  LIST_FETCH_STATUS_CHANGED: 'CATEGORIES_FETCH_STATUS_CHANGED',

  STORES_FETCHED: 'STORES_FETCHED',
  STORES_FETCH_STATUS_CHANGED: 'STORES_FETCH_STATUS_CHANGED',
  PRODUCTS_FETCHED: 'PRODUCTS_FETCHED',
  PRODUCTS_FETCH_STATUS_CHANGED: 'PRODUCTS_FETCH_STATUS_CHANGED',
};

export const getCategoriesStoreFetchStatusAction = (payload) => ({
  type: CATEGORIES.STORES_FETCH_STATUS_CHANGED,
  payload
});

export const getCategoriesProductFetchStatusAction = (payload) => ({
  type: CATEGORIES.PRODUCTS_FETCH_STATUS_CHANGED,
  payload
});

export const CUSTOMER = {
  UNFETCH: 'CUSTOMER_UNFETCH',
  FETCHED: 'CUSTOMER_FETCHED',
  FETCH_STATUS_CHANGED: 'CUSTOMER_FETCH_STATUS_CHANGED',
  LIST_FETCHED: 'CUSTOMERS_FETCHED',
  LIST_FETCH_STATUS_CHANGED: 'CUSTOMERS_FETCH_STATUS_CHANGED',
};

export const getCustomerFetchStatusAction = (payload) => ({
  type: CUSTOMER.FETCH_STATUS_CHANGED,
  payload
});

export const getCustomersListFetchStatusAction = (payload) => ({
  type: CUSTOMER.LIST_FETCH_STATUS_CHANGED,
  payload
});

export const STORE = {
  UNFETCH: 'STORE_UNFETCH',
  FETCHED: 'STORE_FETCHED',
  FETCH_STATUS_CHANGED: 'STORE_FETCH_STATUS_CHANGED',
  PRODUCTS_FETCHED: 'PRODUCTS_FETCHED',
  PRODUCTS_FETCH_STATUS_CHANGED: 'PRODUCTS_FETCH_STATUS_CHANGED',
  LIST_FETCHED: 'STORES_FETCHED',
  LIST_FETCH_STATUS_CHANGED: 'STORES_FETCH_STATUS_CHANGED',
};

export const getStoreFetchStatusAction = (payload) => ({
  type: STORE.FETCH_STATUS_CHANGED,
  payload
});

export const getStoresListFetchStatusAction = (payload) => ({
  type: STORE.LIST_FETCH_STATUS_CHANGED,
  payload
});

export const PRODUCT = {
  UNFETCH: 'PRODUCT_UNFETCH',
  FETCHED: 'PRODUCT_FETCHED',
  FETCH_STATUS_CHANGED: 'PRODUCT_FETCH_STATUS_CHANGED',
  FILTER_CHANGED: 'PRODUCT_FILTER_CHANGED',
  LIST_FETCHED: 'PRODUCTS_FETCHED',
  LIST_FETCH_STATUS_CHANGED: 'PRODUCTS_FETCH_STATUS_CHANGED',
};

export const getProductFetchStatusAction = (payload) => ({
  type: PRODUCT.FETCH_STATUS_CHANGED,
  payload
});

export const getProductsListFetchStatusAction = (payload) => ({
  type: PRODUCT.LIST_FETCH_STATUS_CHANGED,
  payload
});

export const DELIVERY_FIRM = {
  UNFETCH: 'DELIVERY_FIRM_UNFETCH',
  FETCHED: 'DELIVERY_FIRM_FETCHED',
  FETCH_STATUS_CHANGED: 'DELIVERY_FIRM_FETCH_STATUS_CHANGED',
  LIST_FETCHED: 'DELIVERY_FIRMS_FETCHED',
  LIST_FETCH_STATUS_CHANGED: 'DELIVERY_FIRMS_FETCH_STATUS_CHANGED',
};

export const getDeliveryFirmsListFetchStatusAction = (payload) => ({
  type: DELIVERY_FIRM.LIST_FETCH_STATUS_CHANGED,
  payload
});


export const REVIEW = {
  UNFETCH: 'REVIEW_UNFETCH',
  FETCHED: 'REVIEW_FETCHED',
  FETCH_STATUS_CHANGED: 'REVIEW_FETCH_STATUS_CHANGED',
  LIST_FETCHED: 'REVIEWS_FETCHED',
  LIST_FETCH_STATUS_CHANGED: 'REVIEWS_FETCH_STATUS_CHANGED',
};

export const getReviewsListFetchStatusAction = (payload) => ({
  type: REVIEW.LIST_FETCH_STATUS_CHANGED,
  payload
});

export const SEARCH = {
  QUERY_CHANGED: 'QUERY_CHANGED',
};

export const CART = {
  DUMPED: 'CART_DUMPED',
  ITEM_ADDED: 'CART_ITEM_ADDED',
  ITEM_REMOVED: 'CART_ITEM_REMOVED',
  ITEM_QUANTITY_CHANGED: 'CART_ITEM_QUANTITY_CHANGED'
};

export const ORDER = {
  UNFETCH: 'ORDER_UNFETCH',
  FETCHED: 'ORDER_FETCHED',
  FETCH_STATUS_CHANGED: 'ORDER_FETCH_STATUS_CHANGED',
  LIST_FETCHED: 'ORDERS_FETCHED',
  LIST_FETCH_STATUS_CHANGED: 'ORDERS_FETCH_STATUS_CHANGED',
  LIST_STATUS_FILTER_CHANGED: 'ORDERS_STATUS_FILTER_CHANGED',
};

export const getOrdersListFetchStatusAction = (payload) => ({
  type: ORDER.LIST_FETCH_STATUS_CHANGED,
  payload
});

export const PROMOTION = {
  UNFETCH: 'PROMOTION_UNFETCH',
  FETCHED: 'PROMOTION_FETCHED',
  FETCH_STATUS_CHANGED: 'PROMOTION_FETCH_STATUS_CHANGED',
  LIST_FETCHED: 'PROMOTIONS_FETCHED',
  LIST_FETCH_STATUS_CHANGED: 'PROMOTIONS_FETCH_STATUS_CHANGED',
};

export const getPromotionFetchStatusAction = (payload) => ({
  type: PROMOTION.FETCH_STATUS_CHANGED,
  payload
});

export const getPromotionsListFetchStatusAction = (payload) => ({
  type: PROMOTION.LIST_FETCH_STATUS_CHANGED,
  payload
});

export const SAVED_CART = {
  UNFETCH: 'SAVED_CART_UNFETCH',
  FETCHED: 'SAVED_CART_FETCHED',
  FETCH_STATUS_CHANGED: 'SAVED_CART_FETCH_STATUS_CHANGED',
  LIST_FETCHED: 'SAVED_CARTS_FETCHED',
  LIST_FETCH_STATUS_CHANGED: 'SAVED_CARTS_FETCH_STATUS_CHANGED',
};

export const TRANSACTION = {
  UNFETCH: 'TRANSACTION_UNFETCH',
  FETCHED: 'TRANSACTION_FETCHED',
  FETCH_STATUS_CHANGED: 'TRANSACTION_FETCH_STATUS_CHANGED',
  LIST_FETCHED: 'TRANSACTIONS_FETCHED',
  LIST_FETCH_STATUS_CHANGED: 'TRANSACTIONS_FETCH_STATUS_CHANGED',
};

export const getTransactionsListFetchStatusAction = (payload) => ({
  type: TRANSACTION.LIST_FETCH_STATUS_CHANGED,
  payload
});


