
export const ADD_CART_ITEM = 'ADD_CART_ITEM';

export const NAVIGATED = 'NAVIGATED';

export const RESTAURANT_CATEGORIES_FETCHED = 'RESTAURANT_CATEGORIES_FETCHED';

export const FETCH_STATUSES = {
  LOADING: 'LOADING',
  ERROR: 'ERROR',
  EMPTY: 'EMPTY',
  MORE: 'MORE',
  DONE: 'DONE',
};


